<template>
    <div class="statistics">
        <div class="busuanzi">
            <span id="busuanzi_container_site_pv" style="display:none;margin-right: 20px;">
                本站总访问量
                <span id="busuanzi_value_site_pv"></span>次
                <!-- <span class="post-meta-divider">|</span> -->
            </span>
            ❤️
            <span id="busuanzi_container_site_uv" style="display:none;margin-left: 20px;">
                本站访客数
                <span id="busuanzi_value_site_uv"></span>人
            </span>
        </div>
    </div>
</template>
<style>
.statistics {
    text-align: center;
    bottom: 100px;
    position: absolute;
    margin: 0 auto;
    left: 0;
    right: 0;
    color: grey;
    font-size: 15px;
}
</style>