from public.dde_desktop_public_widget.dde_desktop_public_widget import DdeDesktopPublicWidget
from public.dde_dock_public_widget.dde_dock_public_widget import DdeDockPublicWidget
from public.dde_launcher_public_widget.dde_launcher_public_widget import DdeLauncherPublicWidget
from public.right_menu_public_widget.right_menu_public_widget import RightMenuPublicWidget
from public.open_mode_public_widget.open_mode_public_widget import OpenModePublicWidget